[package]
name = "pf-session-authority"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
libc.workspace = true
pf-app-manifest.workspace = true
pf-peer-identity.workspace = true
pf-ports.workspace = true
pf-wire.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
pf-app-launch = { path = "../pf-app-launch" }
